const PRIMARY_COLOR = '#00B9BD';
const PRIMARY_COLOR_DARKER = '#00585B';
const PRIMARY_COLOR_LIGHTER = '#00B9BD';

const colors = {
  PRIMARY_COLOR,
  PRIMARY_COLOR_DARKER,
  PRIMARY_COLOR_LIGHTER,
};

export default colors;
